services:
  front:
    platform: linux/amd64
    container_name: chat_app_front
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    command: ['npm', 'run', 'start']
    env_file:
      - .env.front
    depends_on:
      - api
  api:
    platform: linux/amd64
    container_name: chat_app_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 8080:8080
      - 5555:5555
    command: ['npm', 'run', 'dev']
    env_file:
      - .env.api
    depends_on:
      - db
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: chat_app_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.mysql
volumes:
  db_data:
